# permissions for end users to view foundryvtts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foundryvtt-viewer-role
rules:
- apiGroups:
  - vtt.spichugin.dev
  resources:
  - foundryvtts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vtt.spichugin.dev
  resources:
  - foundryvtts/status
  verbs:
  - get
